# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Srcode < Formula
  desc "Tool that help developers to manage their codebase in an effective & productive way."
  homepage ""
  version "0.1.0"
  license "GPL-3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/creekorful/srcode/releases/download/v0.1.0/srcode_0.1.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "9733f787ab269dd96ca9cd5a9dc00fb17f6ab850333df5a273605ecfea108dec"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/creekorful/srcode/releases/download/v0.1.0/srcode_0.1.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "e1e87d0b7535be171ec4db8500a95ab4cc78131173319446634045a2007f810d"
  end

  depends_on "git"

  def install
    bin.install "srcode"
  end

  test do
    system "#{bin}/srcode --version"
  end
end
